---
- name: Create json file
  template: src=../templates/json/{{ item }} dest=/opt/json/{{ item }}
  with_items:
  - db_conf.json
  - openstack_conf.json
  - rabbitmq.json
  - user_info.json
  become: yes

- name: ADD Rabbitmq vhost
  rabbitmq_vhost:
   name: "{{ rabbitmq_vhost }}"
   node: rabbit@devstack
   state: present
  become: yes

- name: Add Rabbitmq user
  rabbitmq_user:
   user: "{{ rabbitmq_user }}"
   password: "{{ rabbitmq_password }}"
   vhost: "{{ rabbitmq_vhost }}"
   configure_priv: .*
   read_priv: .*
   write_priv: .*
  become: yes

- name: Run Server Container
  docker_container: 
    name: server
    image: getter/monitor-server:pike
    volumes:
    - /opt/json:/opt/go/src/MonitorOpenStackVM/json
  become: yes


